### ISSUE TITLE
Command 145 = Set schedule

### ISSUE THREAD

**Issue by dotJson** [tagyoureit/nodejs-Pentair#13]
I have the wireless remote here and I'm playing around entering different commands and watching the request/response.  I was parsing out my schedules and had two egg timers each at 3 hours.  I set one to two to get the sch number.  I noticed it wrote the update as 91 (hex, my preferred format, decimal 145).  Noticed you didnt have it on your page [https://github.com/tagyoureit/nodejs-Pentair/wiki/Broadcast](url)

**Comment by tagyoureit** [comment]
Awesome, I added it.  Thanks, Jason!
