### ISSUE TITLE
Add ability to create/edit schedules

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-Pentair#18]

**Comment by arrmo** [comment]
Add this to the npm packages? Will be needed for time selections (later),
https://www.npmjs.com/package/timepicker

jQuery UI has datepicker, but not timepicker (odd).

**Comment by tagyoureit** [comment]
Sure. Either you or I can add this.

**Comment by arrmo** [comment]
Done! But leave open for now ... we need the socket.io in place, and sending the info across from the web interface.

**Comment by tagyoureit** [comment]
Moved to https://github.com/tagyoureit/nodejs-poolController/issues/15
