### ISSUE TITLE
Add EggTimer, Pump display to Bootstrap

### ISSUE THREAD

**Issue by arrmo** [tagyoureit/nodejs-Pentair#23]

**Comment by tagyoureit** [comment]
On the circuits, they are also classified as "general" or "lights".  Split out the lights from the other circuits?

**Comment by arrmo** [comment]
I could, NP - what do you prefer? I can just add another panel for this.

**Comment by tagyoureit** [comment]
Egg timer looks great.  Let's add one for the pumps as well.

**Comment by arrmo** [comment]
Working on it right now! ... :).

**Comment by arrmo** [comment]
Actually, I guess this is closed now ... :). Right?

**Comment by tagyoureit** [comment]
Done!
