### ISSUE TITLE
Bootstrap schedules wrap

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-Pentair#26]
Minor adjustment needed as the schedules are wrapping.

![screen shot 2016-10-22 at 11 46 22 pm](https://cloud.githubusercontent.com/assets/1646840/19624569/ebdaeb3e-98b1-11e6-9325-0c2f95e60b63.png)

**Comment by arrmo** [comment]
Agreed! Saw that as well in your pic, thanks for capturing this one. There is a (sort of?) way to customize it right now, but let's take care of bigger items first, then I'll explain how to use the one json file.

**Comment by arrmo** [comment]
Does adjusting the min width in style.css address / correct this? Still trying to find a way to stop wrap, but this may fix it?

**Comment by tagyoureit** [comment]
Yes.  Changing to 600 (from 570px) for me works great.  Maybe on shorter widths the days could appear as a second line under each schedule?  This would save space, as well.  Better for small screens like phones.

**Comment by arrmo** [comment]
I like that! Do we do that by default? It may be cleaner. I'd still like this to auto-adjust (the panel width), but so far it's past my brain capacity ... :(.

**Comment by arrmo** [comment]
Quick hack ... like this? Need to clean up the underline of course.
![image](https://cloud.githubusercontent.com/assets/8756384/19832615/c74ebd36-9ded-11e6-918d-8055b5381069.png)

**Comment by arrmo** [comment]
OK, border removed, padding ("combined" rows) minimized,
![image](https://cloud.githubusercontent.com/assets/8756384/19832804/1a3db2cc-9df3-11e6-9a35-49e29b8aa3bb.png)

**Comment by tagyoureit** [comment]
Love it!  Looks great.  :-)

**Comment by arrmo** [comment]
Will push this sometime this weekend. Thanks!

**Comment by arrmo** [comment]
Closed with latest PR#34 ... close this?

**Comment by tagyoureit** [comment]
Yup, agreed.  I'll close it.
