### ISSUE TITLE
Update time formatting

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-Pentair#37]
Current time formatting coming from the controller/pumps is weak.  It currently might output something like 7:5 for 7:05.  Need to clean this up.

Possible impact on Bootstrap UI.  Right now, 12:05am shows up as 0:05.  Arrmo/tag will coordinate on this.

**Comment by arrmo** [comment]
NP! Just to understand ... can you confirm the format the info is sent across in (for, say, 12 am)?

**Comment by tagyoureit** [comment]
Right now, it's just a X:Y where X is the hours and Y is the minutes.  I think X is 0-23 and Y is 0-59.  Will try to get to this one soon.  Been focusing on a few other bigger items ATM.

**Comment by arrmo** [comment]
No worries - will take care of it on the client side. Thanks!

**Comment by arrmo** [comment]
OK, I can see where this is - fix is quite easy. Just one question though ... is this only on the schedules? Seems to be, just making sure.

For the current time, no formatting done on the client side, and I assume it's not needed ... right?

**Comment by arrmo** [comment]
Pushed a fix (PR #45) - pull it in, check it there? Thanks!

**Comment by tagyoureit** [comment]
One small item.  When it is exactly on the hour (x:00) it displays as x:000.

**Comment by arrmo** [comment]
Will check on it! Is this for clock time, or schedule time?

Thanks.

**Comment by tagyoureit** [comment]
I saw it in the clock time. Didn't check schedules.

**Comment by arrmo** [comment]
Gotcha - thanks! Will dig into it. Right now I can't get any information (socket.io) from server to client - need to get through that first ... :(

**Comment by arrmo** [comment]
Yep, it's there! Had to add the code below to catch it, and let it run until it hit the hour ... :).
		if (data.controllerTime.includes('00'))
			var test=1;

When this did hit, I checked - and data.controllerTime is "6:000 PM" ... so is this actually in index.js?

**Comment by arrmo** [comment]
OK, now also seeing "6:202 PM".

**Comment by tagyoureit** [comment]
I think I fixed it in the last push.  Check it out.

**Comment by arrmo** [comment]
That works! BTW, why is Run Mode and Heater State not passed in 2.0-Alpha?
![image](https://cloud.githubusercontent.com/assets/8756384/20696076/9db405ea-b5b6-11e6-9f62-62ad3362ffd6.png)

**Comment by tagyoureit** [comment]
The heater status comes from the status packet, but because #32 (I'm not sure which one of the bytes correlates to the heater mode vs heater on) I didn't wire it up.  I can hook one of them up and hopefully myself or someone else can figure out exactly what it means.

Run mode... hmmm... I think this might have been something from the pump status early on.  Need to investigate.

Let's open up separate issues for this.  I think we can close the time issue for now.

**Comment by arrmo** [comment]
Works for me - thanks!
