### ISSUE TITLE
Add pump control to Bootstrap

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-Pentair#49]
@arrmo Can you add the pump control to Bootstrap?  You can see the initial iteration at https://github.com/tagyoureit/nodejs-Pentair/blob/master/public/pump.html.

**Comment by arrmo** [comment]
Hi,

Are you thinking inside the Pump Panel (I assume)?

Thanks!

**Comment by tagyoureit** [comment]
Ya... possibly.  But not everyone needs direct control over the pump.  Is it possible to do a "nested" container?  And that can be hidden in the config file for those that have controllers?  Or possibly just a separate one... I'm ok with either until we get some feedback from others that need the pump control.  Personally, I'll keep it hidden.

**Comment by tagyoureit** [comment]
moved to https://github.com/tagyoureit/nodejs-poolController/issues/11
