### ISSUE TITLE
Reconnect to socat

### ISSUE THREAD

**Issue by arrmo** [tagyoureit/nodejs-Pentair#56]
Hi,

One item I have found - if the socat machine / server is rebooted (goes away for a bit), the Node.js server has to be restarted (i.e. restart nodejs-Pentair) once socat is available again. Perhaps automatically reconnect somehow?

Thanks!

**Comment by arrmo** [comment]
Or also - allow for a reconnect request?

**Comment by tagyoureit** [comment]
Moved to https://github.com/tagyoureit/nodejs-poolController/issues/9.
