### ISSUE TITLE
server.key file missing

### ISSUE THREAD

**Issue by GrahamHollis** [tagyoureit/nodejs-Pentair#62]
Built this on both a Pi and an odroid get the same error below on execution. I have a JTEK rs485 attached but not connected to the intelliflo pump yet.

Error: ENOENT: no such file or directory, open '/home/odroid/nodejs-Pentair/lib/comms/../../data/server.key' 

What am I missing? Thanks

**Comment by tagyoureit** [comment]
Hi, the server.key file is something that you provide, with your security & password, etc.  You can create one from a site like http://www.akadia.com/services/ssh_test_certificate.html.

**Comment by GrahamHollis** [comment]
Thanks, that helped me figure out that https is the default setting in config.json. Changed it to http and all is good.
