### ISSUE TITLE
Unable to open RS485 port

### ISSUE THREAD

**Issue by mzuniga51** [tagyoureit/nodejs-Pentair#64]
Hi.  First, thanks to you guys for this fenomenal contribution for us pool enthusiasts.   I have managed to install both the controller and dashboard in my Raspberry and I can access the web interface.  The interface says Ready but it is named Nixie Single Body instead of Intellicenter.  I got no information from the Intellicenter and I get the error found below.   Please let me know if there is anything I am doing wrong.  Is this a software error or can it be an error in my physical connection between my Raspberry Pi and my Intellicenter?  Many thanks.

<img width="809" alt="Screen Shot 2021-09-29 at 21 01 35" src="https://user-images.githubusercontent.com/91519307/135379630-7f854a9b-b19b-4e98-94cd-10d441950e21.png">
!

**Comment by tagyoureit** [comment]
You either don't have an rs485 connector or it isn't found at '/dev/ttyUSB0'. Did you see this [wiki](https://github.com/tagyoureit/nodejs-poolController/wiki/RS-485-Adapter-Details) page?

**Comment by rstrouse** [comment]
Just for shucks turn off Bluetooth on the pi if you are certain that the rs485 adapter is installed properly.  If you have one that connects to the serial interface you need to disable the serial console in the pi configuration and it will be /dev/ttyS0

**Comment by mzuniga51** [comment]
Thank you.  I have change the adapter I was using and now I have success.  However, my pool appear off when is actually on.  Chemistry is also unavailable. The pool pump, however, is showing activity correctly.  Any ideas?
<img width="817" alt="Screen Shot 2021-10-07 at 21 34 05" src="https://user-images.githubusercontent.com/91519307/136494302-d3c285b0-c35c-4ac1-a3a3-b1a7b3db2dff.png">
<img width="812" alt="Screen Shot 2021-10-07 at 21 37 44" src="https://user-images.githubusercontent.com/91519307/136494320-716dcd14-b31b-408b-9301-7e8e973a6ae9.png">
s?
